server: 
  port: 8814
project_station_name: 1104
## 储能单元类型
#energyUnit.type=Storage
## 储能状态
#point.type.state=140000683
## 储能异常发生时间
#point.type.time=140000714
## 主控通信心跳
#point.type.mainBeat=140000717
## 网络通信心跳
#point.type.netBeat=140000715
## 网络状态
#point.type.network=140000716

# 储能状态
point: 
  type: 
    stateName: EnergyStatus
    # 储能异常发生时间
    timeName: AbnormalDatetime
# 机组主控通信心跳
    mainBeatName: MasterHeartbeat
# 机组网络通信心跳
    netBeatName: NetworkHeartbeat
# 机组网络异常状态
    networkName: NetworkAbnormalState

#cn.zju，mqtt，Databus配置
mqtt: 
  mqttServerHost: tcp://192.168.2.37:1883
#mqtt_user=
#mqtt_password=
  appName: cloud_store
  localBeeId: cloud02
  remoteBeeId: #
  settingDir: ./
  logFilter: bus:E gate:E fes:E *:E
#云平台Api接口服务器地址
#retrofit.apiServerUrl=http://172.18.12.138:9998/api/
#websocket配置
wss: 
  server:
    port: 8084
    host: localhost

spring: 
  redis:
    database: 0
    host: 192.168.2.13
    port: 8811
    password: Jhf&*d93jfdKJSf
    pool:
      max-active: 400
      max-wait: 10000
      max-idle: 100
      min-idle: 0
    timeout: 0

j2cache:
  #开启spring cache支持
  open-spring-cache: true
  broadcast: redis
  L1:
    provider_class: caffeine
  L2:
    provider_class: redis
  sync_ttl_to_redis: true
  default_cache_null_object: true
  serialization: json
caffeine:
  region:
    default: 1000, 30m
redis:
  mode: single
  storage: generic
  channel: j2cache
  cluster_name: j2cache
  namespace:
  hosts: 192.168.2.13:8811
  timeout: 2000
  password: Jhf&*d93jfdKJSf
  database: 0
  maxTotal: 100
  maxIdle: 100
  maxWaitMillis: 10000
  minEvictableIdleTimeMillis: 60000
  minIdle: 0
  numTestsPerEvictionRun: 10
  lifo: false
  softMinEvictableIdleTimeMillis: 10
  testOnBorrow: true
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 300000
  blockWhenExhausted: false
  jmxEnabled: false
